version: 0.0
os: linux
files:
  - source: webgoat-server-v8.0.0.jar
    destination: /tmp
hooks:
  BeforeInstall:
    - location: build_docker.sh
      timeout: 300
      runas: root
    - location: build-all.sh
      timeout: 300
      runas: root
      
  AfterInstall:
    - location: clean-run-docker-compose.sh
      timeout: 300
      runas: root
    - location: deploy-webgoat.sh
      timeout: 300
      runas: root
    - location: run-docker-compose.sh
      timeout: 300
      runas: root
    - location: start.sh
      timeout: 300
      runas: root
